### PR TITLE
Update to version 34.0

### LINKED ISSUE #10: Update this feedstock?
### Comment:

Hi,

Seems like there's quite a few things that depends on a conda package for `readme_render` downstream (twine for example), but the lack of updates is causing issues with the latest version of `bleach`.

Is there any chance this package could be updated? I'm happy to see if I can help with maintenance if necessary.

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Bump version and update dependencies:
- bump min version for cmarkgfm
- remove unused six and setuptools

Fix #10

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
@jjhelmus, if you want I could be added as a maintainer

**Comment by tiagofrepereira2012** [comment]
Hi,

Thanks for this PR.
Will this be merged any time soon?

**Comment by tiagofrepereira2012** [comment]
Thanks for the quick reply; much appreciated.

**Pull request merged**
